
#ifndef CASADI_INTERPOLANT_BSPLINE_EXPORT_H
#define CASADI_INTERPOLANT_BSPLINE_EXPORT_H

#ifdef CASADI_INTERPOLANT_BSPLINE_STATIC_DEFINE
#  define CASADI_INTERPOLANT_BSPLINE_EXPORT
#  define CASADI_INTERPOLANT_BSPLINE_NO_EXPORT
#else
#  ifndef CASADI_INTERPOLANT_BSPLINE_EXPORT
#    ifdef casadi_interpolant_bspline_EXPORTS
        /* We are building this library */
#      define CASADI_INTERPOLANT_BSPLINE_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define CASADI_INTERPOLANT_BSPLINE_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef CASADI_INTERPOLANT_BSPLINE_NO_EXPORT
#    define CASADI_INTERPOLANT_BSPLINE_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef CASADI_INTERPOLANT_BSPLINE_DEPRECATED
#  define CASADI_INTERPOLANT_BSPLINE_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef CASADI_INTERPOLANT_BSPLINE_DEPRECATED_EXPORT
#  define CASADI_INTERPOLANT_BSPLINE_DEPRECATED_EXPORT CASADI_INTERPOLANT_BSPLINE_EXPORT CASADI_INTERPOLANT_BSPLINE_DEPRECATED
#endif

#ifndef CASADI_INTERPOLANT_BSPLINE_DEPRECATED_NO_EXPORT
#  define CASADI_INTERPOLANT_BSPLINE_DEPRECATED_NO_EXPORT CASADI_INTERPOLANT_BSPLINE_NO_EXPORT CASADI_INTERPOLANT_BSPLINE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CASADI_INTERPOLANT_BSPLINE_NO_DEPRECATED
#    define CASADI_INTERPOLANT_BSPLINE_NO_DEPRECATED
#  endif
#endif

#endif /* CASADI_INTERPOLANT_BSPLINE_EXPORT_H */
